export const breadcrumbLabels: Record<string, string> = {
  admin: 'Panel de Administración',
  catalog: 'Catálogo',
  historial: 'Historial Médico',
  login: 'Iniciar Sesión',
  quienessomos: 'Sobre Mí',
  servicios: 'Servicios',
  citas: 'Agenda tu Cita',
  politicas: 'Aviso de Privacidad',
  terminos: 'Términos y Condiciones',
  verificacion: 'Verificación',
  recuperacion: 'Recuperación',
  schedule: 'Agendar Cita',
  shopping_cart: 'Carrito',
};
