// All records are synthetic; no real account, clinic database or external service is used.
const patient = { id: 999999, user_id: 999999, nombre_completo: 'Paciente de prueba con apellidos largos', first_name: 'Paciente', second_name: 'de prueba', first_lastname: 'ApellidoLargo', second_lastname: 'SegundoApellido', email: 'correo.muy.largo.para.validar.responsive@example.test', username: 'usuario_ficticio_largo', age: 36, gender: 'F', height: 165, phone: '7710000000', fecha_nacimiento: '1990-01-15', estado_civil: 'Soltero', ocupacion: 'Actividad de prueba', notes: 'Notas ficticias de prueba.' };
const settings = { start_time: '08:00:00', end_time: '18:00:00', lunch_start: '12:00:00', lunch_end: '13:00:00', deposit_amount: 100, disabled_hours: [], is_working_day: true };
const now = new Date(); now.setDate(now.getDate() + 2);
const dateString = now.toISOString().slice(0,10);
const appointment = { id: 999999, patient_id: patient.id, patient_name: patient.nombre_completo, nombre_completo: patient.nombre_completo, first_name: patient.first_name, first_lastname: patient.first_lastname, patient_email: patient.email, appointment_date: dateString, start_time: '09:00:00', end_time: '10:00:00', deposit_paid: true, deposit_amount: 100, status: 'scheduled', payment_status: 'approved', type: 'Consulta de prueba', notes: 'Notas ficticias', has_initial_evaluation: true };
const product = { id: 999999, name: 'Suplemento con nombre largo de prueba', description: 'Descripción ficticia para verificar disposición y acciones.', price: 399, stock: 15, image_url: '/colageno.png', created_at: dateString, categorias: [1] };
const categories = [{ id: 1, name: 'Categoría de prueba' }];
const evaluation = { id: 999999, evaluation_date: dateString, consultation_reason: { main_goal: 'Objetivo de prueba', treatment_expectations: 'Seguimiento de prueba' }, family_history: {}, personal_history: {}, non_pathological_history: {}, dietary_recall: { breakfast: 'Alimento de prueba' }, anthropometric: { weight: 75, body_fat_percentage: 25, muscle_percentage: 30, waist_circumference: 80, hip_circumference: 95, arm_circumference: 28, neck_circumference: 32, blood_pressure_systolic: 120, blood_pressure_diastolic: 80 }, nutritional_diagnosis: { diagnosis: 'Diagnóstico ficticio' }, intervention_plan: { nutritional_goals: 'Objetivo ficticio' }, follow_up: { observations: 'Observaciones ficticias' } };
const meals = ['DESAYUNO','ALMUERZO','COLACION','COMIDA','CENA'];
const plan = { id: 999999, is_active: true, name: 'Plan ficticio', created_at: dateString, meal_times: Object.fromEntries(meals.map(m => [m, {start:'08:00',end:'09:00'}])), menus: Object.fromEntries(['MENU_1','MENU_2','MENU_3','MENU_4'].map(m => [m, {days:['Lunes'],meals:Object.fromEntries(meals.map(t=>[t,{description:'Alimentos ficticios para probar el diseño.'}]))}])) };
const stats = { total: 2, masculinos: 1, femeninos: 1, nuevosUltimos30Dias: 1, totalCitas: 4, citasCompletadas: 2, pesoInicial: 80, pesoActual: 75, todayAppointments: 2, weeklyAppointments: 4, totalPatients: 2, newPatientsMonth: 1, completionRate: 90, nextAppointment: null, weeklyStats: [{day:'Lunes',count:2},{day:'Martes',count:1}], recentPatients: [], weeklyAppointmentsList: [] };
appointment.patient = patient;
const post = {id:999999,title:'Publicación ficticia con título largo',description:'Descripción de prueba',content:'Contenido ficticio para verificar el muro.',username:'cuenta_ficticia',created_at:dateString,updated_at:dateString,views_count:2,likes_count:1,user_has_liked:false,images:[{id:1,url:'/colageno.png'},{id:2,url:'/prowinner.png'}],links:[]};
const table = {nombre_tabla:'tabla_ficticia',tamano_total_humano:'1 MB',tamano_datos_humano:'500 kB',tamano_indices_humano:'500 kB',numero_filas:10,filas_estimadas:10,porcentaje_total:50,tamano_humano:'1 MB',porcentaje:50};
const metrics = {sesiones_activas:{total:1,detalle:[]},tamano_total:{humano:'2 MB',detalle_por_tabla:[table]},tablas_mas_pesadas:[table],estadisticas:{conexiones_actuales:1,conexiones_maximas:100,total_tablas:2,total_indices:2,total_vistas:0,ultimo_vacuum:null,ultimo_analyze:null}};
module.exports = { patient, settings, appointment, product, categories, evaluation, plan, stats, dateString, post, metrics };
