// A self-contained public shell: no session, database data, RSC payload or remote font.
export const dynamic = 'force-static';

export function GET() {
  return new Response(`<!doctype html>
<html lang="es-MX"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#6B8E7B"><title>Sin conexión | Rubí Ramos</title><link rel="manifest" href="/manifest.json"><link rel="icon" href="/icons/icon-192x192.png">
<style>*{box-sizing:border-box}body{margin:0;min-height:100dvh;display:grid;place-items:center;padding:max(1rem,env(safe-area-inset-top)) max(1rem,env(safe-area-inset-right)) max(1rem,env(safe-area-inset-bottom)) max(1rem,env(safe-area-inset-left));background:#FAF9F7;color:#2C3E34;font-family:system-ui,sans-serif;overflow-wrap:anywhere}main{width:100%;max-width:30rem;padding:clamp(1.5rem,5vw,3rem);background:white;border:1px solid #E6E3DE;border-radius:1.5rem;box-shadow:0 8px 32px #2C3E340d;text-align:center}img{max-width:100%;height:auto;width:220px}.symbol{margin:2rem auto 1rem;width:4rem;height:4rem;display:grid;place-items:center;border-radius:50%;background:#6B8E7B1a;color:#5A8C7A;font-size:2rem}h1{font-size:clamp(1.75rem,6vw,2.25rem);margin:1rem 0}p{line-height:1.6;color:#6E7C72}.retry{display:flex;align-items:center;justify-content:center;min-height:48px;margin:1.5rem 0 0;padding:.75rem 1rem;border-radius:.75rem;background:#5A8C7A;color:white;font-weight:600;text-decoration:none}.retry:hover{background:#2C3E34}a:focus-visible{outline:3px solid #F58634;outline-offset:4px}.note{font-size:.875rem;margin-top:1.5rem;border-top:1px solid #E6E3DE;padding-top:1rem}footer a{color:#2C3E34;display:inline-block;padding:.5rem}</style></head>
<body><main><img src="/logo_rubi.png" alt="Consultorio Rubí Ramos" width="220" height="41"><div class="symbol" aria-hidden="true">↻</div><h1>Sin conexión</h1><p>Revisa tu conexión a internet e inténtalo nuevamente.</p><a class="retry" href="/">Reintentar</a><p class="note">Para consultar citas, expedientes, planes alimenticios o pagos necesitas conexión. Tu información privada no se guarda para uso offline.</p><footer><a href="tel:+527717206956">+52 77 1720 6956</a><br><a href="mailto:contacto@rubinutricion.com">contacto@rubinutricion.com</a></footer></main></body></html>`, {
    headers: { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'public, max-age=0, must-revalidate' },
  });
}
